### ISSUE TITLE
Adding A Custom Repo

### ISSUE THREAD

**Issue by VannaDii** [cowboyrushforth/home-assistant-molekule#1]
Your repository doesn't want to add to the add-on store.

<img width="613" alt="image" src="https://github.com/user-attachments/assets/d6946f84-b167-426a-bb28-5952dd98ed63">

**Comment by cowboyrushforth** [comment]
Hrm, that is weird, I ust tried to delete it and re-add it, and it worked fine for me.

are you adding it as an "integration"?

i used url: https://github.com/cowboyrushforth/home-assistant-molekule.git

**Comment by VannaDii** [comment]
I'm using a Home Assistant Green with the latest updates applied and I don't have a `type` selector when I add a repo. I've attached a video in case it helps. 

https://github.com/user-attachments/assets/1879b36e-7c6b-4388-a480-1080033a9aee

**Comment by cowboyrushforth** [comment]
are you adding it to "Add-ons", or to "HACS" ?  this is an integration to be added thru HACS, not an "add-on".

**Comment by VannaDii** [comment]
🤦🏻‍♀️ I was adding it to add-ons. It works great, as long as you use HACS lol. Sorry about the issue

**Comment by cowboyrushforth** [comment]
no problem, let me know if you have any issues.

**Comment by VannaDii** [comment]
No issues so far. Was able to add two Molekule air pros into HomeKit via HA and it seems to work great.

Thanks for the awesome integration!!
